name: Publish package

on:
  push:
    branches:
      - ci

jobs:
  publish-npm:
    strategy:
      max-parallel: 1
      matrix: 
        plugins: ['time-saver', 'time-saver-backend', 'time-saver-common']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn install

      - name: Run tests and build
        run: |
          yarn tsc
          yarn run clean
          yarn run build
          yarn run test

      - name: Publish npm package
        run: |
           export PUBLISH=$(if [ "$(npm view $(cut -d "=" -f 2 <<< $(npm run env | grep "npm_package_name")) version)" == "$(cut -d "=" -f 2 <<< $(npm run env | grep "npm_package_version"))" ]; then echo false; else echo true; fi)
           echo $PUBLISH
           if [ "$PUBLISH" == true ]; then npm publish --dry-run ; else echo "since release not created not publishing the package"; fi
        working-directory: ./plugins/${{ matrix.plugins }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}