name: Node.js Package


on:
  push:
    branches:
      - ci

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check for changes in plugin directories
        id: check_changes
        run: |
          directories=$(git diff --name-only main...HEAD | grep -E '^plugins/[^/]+/' | cut -d/ -f2 | sort -u)
          for dir in $directories; do
            if [ -d "plugins/$dir" ]; then
              echo "Changes detected in plugins/$dir directory."
              cd "plugins/$dir"
              npm publish
              cd ../..
            fi
          done
      - name: Set output if changes detected
        if: steps.check_changes.outputs.changes != ''
        run: echo "::set-output name=changes::true"
      - name: Set output if no changes detected
        if: steps.check_changes.outputs.changes == ''
        run: echo "::set-output name=changes::false"